services:
  server-web:
    build: .
    init: true
    environment:
      - SERVER_WEB__CONFIG_DIR=/server-web/config
    ports:
      - 4180:4180
    volumes:
      - ./config/server-web/:/server-web/config:ro
