[graph]
all-features        = true
no-default-features = false

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "Unicode-3.0"]

[licenses.private]
ignore = true

[bans]
deny                       = ["openssl", "openssl-sys", "rustls-webpki"]
external-default-features  = "allow"
highlight                  = "all"
workspace-default-features = "allow"
