name: Rust

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta
          components: clippy

      - name: Linting
        run: cargo clippy -- -D warnings

  deny:
    name: deny
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta
          components: clippy

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Deny
        run: cargo deny --workspace --all-features --locked check

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta
          components: rustfmt

      - name: Enforce formatting
        run: cargo fmt --check

  taplo:
    name: taplo
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta

      - name: Install taplo
        run: cargo install taplo-cli

      - name: Validate TOML files
        run: taplo format --check

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta

      - name: Run tests
        run: cargo test --workspace --all-features --locked
